/*

 BACKGROUND_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\users\matthew\My Documents\gb_games\skateboard\spritefiles\backgroundsprites.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __background_map_h_INCLUDE
#define __background_map_h_INCLUDE

#define background_mapWidth 20
#define background_mapHeight 18
#define background_mapBank 0

extern const unsigned char background_map[];

#endif

/* End of BACKGROUND_MAP.H */
