/*

 BIRDSPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 1

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char bird[] =
{
  0x01,0x01,0x07,0x01,0x1A,0x3F,0x77,0x3F,
  0x3F,0x07,0x02,0x03,0x01,0x01,0x01,0x01,
  0x80,0x80,0x82,0xC1,0xDB,0xE7,0xFE,0xFF,
  0xFC,0xFA,0xE0,0xF0,0xC0,0xE0,0xC0,0x80
};

/* End of BIRDSPRITE.C */
